Repository near/docs, pull requests merged in 2023-02, with the labels that each got.

#1352 Add trx signing and sending explanation
  docs/4.tools/near-api-js/faq.md
Labels: enhancement

#1360 Bump tsconfig lib target to ES2018
  docs/3.tutorials/indexer/js-lake-indexer.md
Labels: bug

#1361 docs: Add thousands separators to Gas
  docs/sdk/rust/cross-contract/callbacks.md
Labels: C-docs
